name: 'The Money Orchard, Inc.'
favicon: null
layout_spectrum: 0.99579
typography_spectrum: 0.49519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#7f7f7f'
    - '#3f3f3f'
    - '#e02a42'
  brandStrength: 0.6345376020763069
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
