name: 'The Money Orchard, Inc.'
favicon: null
layout_spectrum: 0.8190696111414582
typography_spectrum: 0.879513812949881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6345376020763069
  lightness: 0.9394444874487817
  saturation: 0.2393031211104244
  rhythmicContrast: 0.6270593795925379
purpose: []
